resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/12/21.yaml

packages:
- .

extra-deps: []

# Override default flag values for local packages and extra-deps
# flags: {}
