resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/12/21.yaml

packages:
- .

extra-deps:
- hprotoc-2.4.12
- protocol-buffers-2.4.12
- protocol-buffers-descriptor-2.4.12

# Override default flag values for local packages and extra-deps
# flags: {}
